# file: roles/mongodb/tasks/main.yml

#
# This playbook installed the mongodb.
#

# MongoDB
- name: Install mongodb
  apt: name={{item}} state=installed
  with_items:
    - mongodb
    - mongodb-clients
    - mongodb-server
