# file: app-server.yml

#
# This the playbook installs an application server.
# It must be run as privileged user.
#

- import_playbook: main.yml

- hosts: servers
  become: yes
  become_method: sudo
  roles:
    - postfix
    - java
    - apache2
#    - tomcat
