# file: dev-server.yml

#
# This the playbook installs an development server.
# It must be run as privileged user.
#

- import_playbook: main.yml

- hosts: servers
  become: yes
  become_method: sudo
  roles:
    - java
    - docker
    - docker-compose
    - docker-registry
    - docker-cleanup
    - docker-maven
    - docker-adminer
    - docker-postgres

    # Optional extentions
    - docker-jenkins
    - docker-sonarqube
    
    # choose an management tool for docker container
    #- portainer
    #- rancher

# TODO adding nfs shares for docker machines
#    - name: Updating system
#      apt: 
#        update_cache: yes
#
#    - name: Install nfs-common
#      apt:
#        name: nfs-common
#        state: present
#
#    - name: Create target directory
#      file:
#        path: '{{ target }}' 
#        state: directory
#        mode: 0755
#
#    - name: Installing and mounting share
#      mount:
#        name: '{{ target }}'
#        src: '{{ share }}'
#        fstype: nfs
#        state: mounted
