# file: roles/tomcat/handlers/main.yml

#
# This handlers are used for the tomcat installation.
#

# Restart tomcat
- name: restart tomcat8
  service:
    name: tomcat8
    state: restarted

- name: tomcat user created
  debug:
    msg: "Created tomcat user {{ tomcat_user }} with password {{ tomcat_password }}"
