# file: roles/docker-cleanup/tasks/main.yml

#
# This playbook deploy portainer as meltwater/docker-cleanup.
#

# docker-cleanup
 - name: Deploy container meltwater/docker-cleanup
   docker_container:
    name: docker-cleanup
    image: meltwater/docker-cleanup:latest
    state: started
    restart_policy: always
    privileged: yes
    volumes:
      - /var/lib/docker:/var/lib/docker:rw
      - /var/run/docker.sock:/var/run/docker.sock:rw
