# file: roles/common/tasks/main.yml

#
# This playbook installed and configure the common packages of the server.
#

# Install system updates
- name: Update all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist

# Install system tools
- name: Install htop
  apt:
    name: htop
- name: Install iotop
  apt:
    name: iotop
- name: Install iftop
  apt:
    name: iftop
- name: Install mc
  apt:
    name: mc
- name: Install wget
  apt:
    name: wget
- name: Install ca-certificates
  apt:
    name: ca-certificates
- name: Install curl
  apt:
    name: curl
- name: Install rsync
  apt:
    name: rsync
- name: Install git
  apt:
    name: git
- name: Install software-properties-common
  apt:
    name: software-properties-common
- name: Install python-software-properties
  apt:
    name: python-software-properties
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
- name: Install screen
  apt:
    name: screen

# Creating users with groups
- name: Create group for admin
  group:
    name: "{{ admin_user }}"
- name: Create admin user
  user:
    name: "{{ admin_user }}"
    password: "{{ admin_password }}"
    group: "{{ admin_user }}"
    shell: /bin/bash
  notify:
    - admin user created
- name: Grant admin rights
  lineinfile:
    path: "/etc/sudoers.d/{{ admin_user }}"
    create: yes
    state: present
    regexp: "^{{ admin_user }} ALL="
    line: "{{ admin_user }} ALL=(ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"

- name: Create group for application
  group:
    name: "{{ application_user }}"
- name: Create application user
  user:
    name: "{{ application_user }}"
    password: "{{ application_password }}"
    group: "{{ application_user }}"
    shell: /bin/bash
  notify:
    - application user created
