---
# This playbook shutdowns servers
- hosts: '{{ hosts }}'
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Shutdown machine
      shell: sleep 2 && shutdown -P now "Ansible updates triggered"
      async: 1
      poll: 0
      ignore_errors: true
