---
# This playbook updates all servers
- hosts: '{{ hosts }}'
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      apt:
        update_cache: yes
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: restart machine
      shell: sleep 2 && shutdown -r now "Ansible restart after updating triggered"
      async: 1
      poll: 0
      ignore_errors: true
